[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/create-donation"
  to = "/.netlify/functions/create-donation"
  status = 200
  force = true

[[redirects]]
  from = "/api/subscribe"
  to = "/.netlify/functions/subscribe"
  status = 200
  force = true

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/track-view"
  to = "/.netlify/functions/track-view"
  status = 200
  force = true
